;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2011/5/17 17:33:07

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1000	1000	; 主菜单 主菜单\主菜单.htm
#define IDH_1001	1001	; 客服管理 客服管理.htm
#define IDH_1011	1011	; 开户 客服管理\客服管理.htm
#define IDH_1025	1025	; 业务受理  客服管理\业务受理.htm
#define IDH_1056	1056	; 营业日志管理  客服管理\营业日志管理.htm
#define IDH_1055	1055	; 对账管理  客服管理\对账管理.htm
#define IDH_1002	1002	; 统计管理 统计管理\统计管理.htm
#define IDH_1048	1048	; 互动消费信息统计  统计管理\互动消费信息统计.htm
#define IDH_1003	1003	; 消息管理 消息管理\消息管理.htm
#define IDH_1014	1014	; 邮件管理  消息管理\邮件管理.htm
#define IDH_1015	1015	; OSD管理  消息管理\OSD管理.htm
#define IDH_1004	1004	; 资源管理 资源管理\资源管理.htm
#define IDH_1018	1018	; IC卡管理  资源管理\IC卡管理.htm
#define IDH_1019	1019	; 机顶盒管理  资源管理\机顶盒管理.htm
#define IDH_1020	1020	; 机卡绑定  资源管理\机卡绑定.htm
#define IDH_1022	1022	; 库存管理  资源管理\库存管理.htm
#define IDH_1016	1016	; 定期提醒管理  消息管理\定期提醒管理.htm
#define IDH_1005	1005	; 产品管理 产品管理\产品管理.htm
#define IDH_1023	1023	; 服务管理 服务管理.htm
#define IDH_1021	1021	; 服务分类  产品管理\服务分类.htm
#define IDH_1049	1049	; 服务信息管理  产品管理\服务信息管理.htm
#define IDH_1050	1050	; 服务升级  产品管理\服务升级.htm
#define IDH_1051	1051	; 服务下架  产品管理\服务下架.htm
#define IDH_1052	1052	; 服务退出  产品管理\服务退出.htm
#define IDH_1053	1053	; 套餐信息管理  产品管理\套餐信息管理.htm
#define IDH_1007	1007	; 账单管理 账单管理\账单管理.htm
#define IDH_1030	1030	; 用户账单管理 账单管理\用户账单管理.htm
#define IDH_1061	1061	; 用户类型催缴规则管理 账单管理\用户类型催缴规则管理.htm
#define IDH_1062	1062	; 任务类型管理 账单管理\任务类型管理.htm
#define IDH_1063	1063	; 财务任务管理 账单管理\财务任务管理.htm
#define IDH_1064	1064	; 银行代扣管理 账单管理\银行代扣管理.htm
#define IDH_1060	1060	; 催缴单管理 账单管理\催缴单管理.htm
#define IDH_1008	1008	; 系统配置 系统配置\系统配置.htm
#define IDH_1010	1010	; 营业类别管理 系统配置\营业类别管理.htm
#define IDH_1031	1031	; 费用类型管理 系统配置\费用类型管理.htm
#define IDH_1036	1036	; 业务系统配置管理 系统配置\业务系统配置管理.htm
#define IDH_1033	1033	; 业务权限接口管理 系统配置\业务权限接口管理.htm
#define IDH_1057	1057	; 业务系统管理 系统配置\业务系统管理.htm
#define IDH_1032	1032	; 设备对应收费管理 系统配置\设备对应收费管理.htm
#define IDH_1034	1034	; 片区管理 系统配置\片区管理.htm
#define IDH_1035	1035	; 营业单位管理 系统配置\营业单位管理.htm
#define IDH_1009	1009	; 系统管理 系统管理\系统管理.htm
#define IDH_1058	1058	; 基本功能管理 系统管理\基本功能管理.htm
#define IDH_1037	1037	; 功能角色管理 系统管理\功能角色管理.htm
#define IDH_1038	1038	; 数据权限组管理 系统管理\数据权限组管理.htm
#define IDH_1039	1039	; 人事角色管理 系统管理\人事角色管理.htm
#define IDH_1040	1040	; 功能角色权限配置 系统管理\功能角色权限配置.htm
#define IDH_1041	1041	; 人事角色权限配置 系统管理\人事角色权限配置.htm
#define IDH_1042	1042	; 系统用户管理 系统管理\系统用户管理.htm
#define IDH_1043	1043	; 个人信息维护 系统管理\个人信息维护.htm
#define IDH_1044	1044	; 插件管理 系统管理\插件管理.htm
#define IDH_1045	1045	; 扩展点信息管理 系统管理\扩展点信息管理.htm
#define IDH_1046	1046	; 系统参数配置 系统管理\系统参数管理.htm
#define IDH_1047	1047	; 参数配置 系统管理\参数配置.htm
